---
name: deploy Website with Surge

on: 
  push:
    branches:
      - master
  
  jobs: 
    build: 
      name: Job_Deploy_Surge
      runs-on: ubuntu-latest
      steps:
        -uses: actions/checkout@v2
        -name: Setup Node
         uses: actions/setup-node@v2-beta
         with:
          node-versions: '12'
        - name: Setup Surge
          run: npm install --global surge
        - name: Execute deployment with surge
          run: surge ./ bootcamp-setup-itsmewaqar.surge.sh --token ${{ secrets.SURGE}}

...